# Use the common base image
FROM mybaseimage:latest

# Set the working directory
WORKDIR /usr/src/app

# Copy application-specific code
COPY . .

# Expose the necessary port
EXPOSE 5002

# Run the application
CMD ["python", "clean_text.py"]
